# ruff: noqa: E501, SLF001
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: diarize.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor  # type: ignore[import-untyped]
from google.protobuf import descriptor_pool as _descriptor_pool  # type: ignore[import-untyped]
from google.protobuf import runtime_version as _runtime_version  # type: ignore[import-untyped]
from google.protobuf import symbol_database as _symbol_database  # type: ignore[import-untyped]
from google.protobuf.internal import builder as _builder  # type: ignore[import-untyped]

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'diarize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rdiarize.proto\x12\x10services.diarize"\x1c\n\x0c\x41udioRequest\x12\x0c\n\x04path\x18\x01 \x01(\t"6\n\x07Segment\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x12\x0f\n\x07speaker\x18\x03 \x01(\t"@\n\x11\x44iarizationResult\x12+\n\x08segments\x18\x01 \x03(\x0b\x32\x19.services.diarize.Segment2U\n\x07\x44iarize\x12J\n\x03Run\x12\x1e.services.diarize.AudioRequest\x1a#.services.diarize.DiarizationResultb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diarize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_AUDIOREQUEST']._serialized_start = 35
    _globals['_AUDIOREQUEST']._serialized_end = 63
    _globals['_SEGMENT']._serialized_start = 65
    _globals['_SEGMENT']._serialized_end = 119
    _globals['_DIARIZATIONRESULT']._serialized_start = 121
    _globals['_DIARIZATIONRESULT']._serialized_end = 185
    _globals['_DIARIZE']._serialized_start = 187
    _globals['_DIARIZE']._serialized_end = 272
# @@protoc_insertion_point(module_scope)
