# ruff: noqa: E501, SLF001
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summarize.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor  # type: ignore[import-untyped]
from google.protobuf import descriptor_pool as _descriptor_pool  # type: ignore[import-untyped]
from google.protobuf import runtime_version as _runtime_version  # type: ignore[import-untyped]
from google.protobuf import symbol_database as _symbol_database  # type: ignore[import-untyped]
from google.protobuf.internal import builder as _builder  # type: ignore[import-untyped]

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'summarize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fsummarize.proto\x12\x12services.summarize"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t"\x17\n\x07Summary\x12\x0c\n\x04text\x18\x01 \x01(\t2P\n\tSummarize\x12\x43\n\x03Run\x12\x1f.services.summarize.TextRequest\x1a\x1b.services.summarize.Summaryb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summarize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_TEXTREQUEST']._serialized_start = 39
    _globals['_TEXTREQUEST']._serialized_end = 66
    _globals['_SUMMARY']._serialized_start = 68
    _globals['_SUMMARY']._serialized_end = 91
    _globals['_SUMMARIZE']._serialized_start = 93
    _globals['_SUMMARIZE']._serialized_end = 173
# @@protoc_insertion_point(module_scope)
