# ruff: noqa: E501, SLF001
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcribe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor  # type: ignore[import-untyped]
from google.protobuf import descriptor_pool as _descriptor_pool  # type: ignore[import-untyped]
from google.protobuf import runtime_version as _runtime_version  # type: ignore[import-untyped]
from google.protobuf import symbol_database as _symbol_database  # type: ignore[import-untyped]
from google.protobuf.internal import builder as _builder  # type: ignore[import-untyped]

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, '', 'transcribe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10transcribe.proto\x12\x13services.transcribe"\x1c\n\x0c\x41udioRequest\x12\x0c\n\x04path\x18\x01 \x01(\t"\x1a\n\nTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t2W\n\nTranscribe\x12I\n\x03Run\x12!.services.transcribe.AudioRequest\x1a\x1f.services.transcribe.Transcriptb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_AUDIOREQUEST']._serialized_start = 41
    _globals['_AUDIOREQUEST']._serialized_end = 69
    _globals['_TRANSCRIPT']._serialized_start = 71
    _globals['_TRANSCRIPT']._serialized_end = 97
    _globals['_TRANSCRIBE']._serialized_start = 99
    _globals['_TRANSCRIBE']._serialized_end = 186
# @@protoc_insertion_point(module_scope)
