name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: voicerec
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install uv
        run: pip install uv

      - name: Install project dependencies
        run: |
          chmod +x install_deps.sh
          ./install_deps.sh

      - name: Ruff check
        run: uv run ruff check --fix .
        working-directory: backend

      - name: Ruff format
        run: uv run ruff format .
        working-directory: backend

      - name: Mypy
        run: uv run mypy .
        working-directory: backend

      - name: Frontend lint
        run: npm run lint
        working-directory: frontend

      - name: Backend tests
        run: uv run pytest
        working-directory: backend

      - name: Frontend tests
        run: npm test
        working-directory: frontend
